In [2]:
import numpy as np
import sys

# The basics

In [3]:
a = np.array([1,2,3])
a

array([1, 2, 3])

In [3]:
b = np.array([[9.0, 5.0, 6.0], [6.5, 9.5, 8.5]])
b

array([[9. , 5. , 6. ],
       [6.5, 9.5, 8.5]])

# Get Dimension

In [4]:
a.ndim

1

In [5]:
b.ndim

2

# Get Shape

In [7]:
a.shape

(3,)

In [9]:
b.shape

(2, 3)

# Get Type

In [11]:
a.dtype

dtype('int32')

In [12]:
b.dtype

dtype('float64')

In [13]:
new_a = a = np.array([1,2,3], dtype='int16')

In [15]:
new_a.dtype

dtype('int16')

# Get Size of each element

In [16]:
a.itemsize

2

In [17]:
new_a.itemsize

2

In [18]:
b.itemsize

8

# Get Total Size

In [19]:
a.nbytes

6

In [20]:
b.nbytes

48

In [21]:
new_a.nbytes

6

# Accessing/Changing specific elements, rows, columns, etc

In [22]:
a = np.array([[1, 2, 3, 4, 5, 6, 7], [8, 9, 10, 11, 12, 13, 14]])
a

array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14]])

In [23]:
a.shape

(2, 7)

In [24]:
# Get a specific element [r, c]
a[1, 5]

13

In [25]:
a[1, -2]

13

In [26]:
# Get a specific row
a[0, :]

array([1, 2, 3, 4, 5, 6, 7])

In [27]:
# Get a specific column
a[:, 2]

array([ 3, 10])

In [28]:
# [startindex:endindex:stepsize]
a[0, 1:6:2]

array([2, 4, 6])

In [29]:
# Change
a[1,5] = 20

In [30]:
a

array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 20, 14]])

In [31]:
a[:, 2] = 5

In [32]:
a

array([[ 1,  2,  5,  4,  5,  6,  7],
       [ 8,  9,  5, 11, 12, 20, 14]])

In [33]:
a[:, 2] = [1,2]

In [34]:
a

array([[ 1,  2,  1,  4,  5,  6,  7],
       [ 8,  9,  2, 11, 12, 20, 14]])

In [35]:
# 3D Example
b = np.array([[[1,2], [3, 4]], [[5,6], [7, 8]]])
b

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [39]:
# Work from outmost to innermost
b[0, 1, 1]

4

# Initialize different types of arrays

In [42]:
# All 0s matrix
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [43]:
np.zeros((2, 3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [44]:
np.zeros((2, 3, 3))

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

In [46]:
np.zeros((2, 3, 3, 2))

array([[[[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]]]])

In [47]:
# All 1s matrix
np.ones(2)

array([1., 1.])

In [48]:
np.ones((2,3), dtype='int32')

array([[1, 1, 1],
       [1, 1, 1]])

In [50]:
# Any other number
np.full((2, 2), 99, dtype='float32')

array([[99., 99.],
       [99., 99.]], dtype=float32)

In [51]:
# Any other number (full_like)
np.full_like(a, 4)

array([[4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4]])

In [52]:
# Random decimal numbers
np.random.rand(4,2)

array([[0.68967806, 0.65494993],
       [0.62110812, 0.62267807],
       [0.29136062, 0.99597318],
       [0.58374075, 0.54219704]])

In [54]:
# Random integer values
np.random.randint(7)

2

In [55]:
np.random.randint(7, size=(3,3)) #Start from 0 to 6

array([[3, 6, 3],
       [0, 1, 1],
       [3, 6, 2]])

In [70]:
np.random.randint(4, 7, size=(3,3)) #Start from 4 to 6

array([[6, 5, 5],
       [6, 5, 4],
       [5, 5, 4]])

In [71]:
# The identity matrix
np.identity(3) # Only one parameter because it is a square matrix

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [72]:
np.identity(9)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [74]:
# Repeat the array
arr = np.array([1,2,3])
r1 = np.repeat(arr, 3)
r1

array([1, 1, 1, 2, 2, 2, 3, 3, 3])

In [76]:
arr = np.array([[1,2,3]])
r1 = np.repeat(arr, 3, axis=0)
r1

array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])

# Practice question 1

In [85]:
output = np.ones((5,5), dtype='int32')

z = np.zeros((3,3), dtype='int32')
z[1,1] = 9
output[1:4, 1:4] = z
output

array([[1, 1, 1, 1, 1],
       [1, 0, 0, 0, 1],
       [1, 0, 9, 0, 1],
       [1, 0, 0, 0, 1],
       [1, 1, 1, 1, 1]])

# Mathematics

In [86]:
a = np.array([1,2,3,4])
a

array([1, 2, 3, 4])

In [87]:
a+2

array([3, 4, 5, 6])

In [88]:
a-2

array([-1,  0,  1,  2])

In [89]:
a*2

array([2, 4, 6, 8])

In [90]:
a/2

array([0.5, 1. , 1.5, 2. ])

In [91]:
a

array([1, 2, 3, 4])

In [92]:
a%2

array([1, 0, 1, 0], dtype=int32)

In [93]:
b = np.array([1,0,1,0])
a+b

array([2, 2, 4, 4])

In [94]:
a**2

array([ 1,  4,  9, 16], dtype=int32)

In [95]:
np.sin(a)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

In [96]:
np.cos(a)

array([ 0.54030231, -0.41614684, -0.9899925 , -0.65364362])

In [97]:
np.tan(a)

array([ 1.55740772, -2.18503986, -0.14254654,  1.15782128])

# Linear Algebra

In [102]:
a = np.ones((2,3))
a

array([[1., 1., 1.],
       [1., 1., 1.]])

In [104]:
b = np.full((3,2), 2)
b

array([[2, 2],
       [2, 2],
       [2, 2]])

In [105]:
np.matmul(a,b)

array([[6., 6.],
       [6., 6.]])

In [106]:
# Find the determinant
c = np.identity(3)
np.linalg.det(c)

1.0

# Statistics

In [107]:
stats = np.array([[1,2,3], [4,5,6]])
stats

array([[1, 2, 3],
       [4, 5, 6]])

In [109]:
np.min(stats)

1

In [110]:
np.max(stats)

6

In [114]:
np.min(stats, axis=1) # Min of the first row and min of the second row

array([1, 4])

In [115]:
np.sum(stats)

21

# Reorganizing Arrays

In [116]:
before = np.array([[1,2,3,4], [5,6,7,8]])
before

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [117]:
before.shape

(2, 4)

In [118]:
after = before.reshape((8,1))
after

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8]])

# Vertical Stacks

In [121]:
v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])
np.vstack([v1,v2])

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

# Horizontal Stack

In [122]:
np.hstack([v1,v2])

array([1, 2, 3, 4, 5, 6, 7, 8])

# Miscellaneous

In [123]:
v1 > 2

array([False, False,  True,  True])

In [124]:
v1[v1 > 2]

array([3, 4])

### You can index with a list in NumPy

In [125]:
a = np.array([1,2,3,4,5,6,7,8,9])
a[[1,2,8]]

array([2, 3, 9])