# NumPy Exercises 

#### Import NumPy as np

In [4]:
import numpy as np

#### Create an array of 10 zeros 

In [13]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### Create an array of 10 ones

In [12]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

#### Create an array of 10 fives

In [10]:
np.full(10, 5)

array([5, 5, 5, 5, 5, 5, 5, 5, 5, 5])

#### Create an array of the integers from 10 to 50

In [14]:
np.arange(10, 51)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

#### Create an array of all the even integers from 10 to 50

In [15]:
np.arange(10, 52, 2)

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

#### Create a 3x3 matrix with values ranging from 0 to 8

In [19]:
np.array([[0,1,2], [3,4,5], [6,7,8]])

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### Create a 3x3 identity matrix

In [20]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### Use NumPy to generate a random number between 0 and 1

In [69]:
np.random.rand()

0.17233828536872953

#### Create the following matrix:

#### Create an array of 20 linearly spaced points between 0 and 1: 

(Hint: Use linspace function)

In [70]:
np.linspace(0,1, num=20)

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

## Numpy Indexing and Selection

You are given this matrix named mat. Write some code to get the outputs accordingly in the cells given below

In [72]:
mat = np.arange(1,26).reshape(5,5)
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

#### Get the sum of all the values in mat

In [74]:
np.sum(mat)

325

#### Get the standard deviation of the values in mat

In [76]:
np.std(mat)

7.211102550927978

#### Get the sum of all the columns in mat

In [75]:
sum = 0
for num in mat:
    sum = sum + num
sum

array([55, 60, 65, 70, 75])